# Étape de build (avec Maven)
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app

# Copier le fichier pom.xml et le wrapper Maven
COPY pom.xml .
COPY mvnw .
COPY .mvn/ .mvn/

# Rendre le wrapper Maven exécutable et télécharger les dépendances Maven
RUN chmod +x mvnw && mvn dependency:go-offline -B

# Copier le code source
COPY src/ src/

# Compiler le projet avant les tests
RUN ./mvnw clean install -DskipTests

# Définir le profil actif pour les tests
ENV SPRING_PROFILES_ACTIVE=test

# Exécuter les tests avec le profil "test"
CMD ["./mvnw", "test", "-Ptest"]